### PR TITLE
Upgrade to latest react and remove use of its internal dependency

### PR DESCRIPTION
**Pull request by haf**

### CODE REVIEW

**Comment by Brian-Kaplan** [comment]
so is this repo dead or something...

**Comment by haf** [comment]
Probably close to it, but if you fork it I can PR towards your repo.

**Comment by fdecampredon** [comment]
Sorry I don't have time ATM to maintain this repo.
However the only real useful part of this repo is `funcSubject` which is like 3 lines of code, so you should probably create your own version and stick with it

**Comment by Brian-Kaplan** [comment]
@fdecampredon thanks for the quick response, ill do that.

**Pull request closed without merging**
